# Generated by Django 5.2.7 on 2025-11-05 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(max_length=512, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido1', models.CharField(max_length=50)),
                ('apellido2', models.CharField(blank=True, max_length=50, null=True)),
                ('documento', models.CharField(max_length=50, unique=True)),
                ('tipo_documento', models.IntegerField(choices=[(1, 'DNI'), (2, 'Pasaporte')], default=2)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('alta', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(max_length=512, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido1', models.CharField(max_length=50)),
                ('cargo', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(max_length=512, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido1', models.CharField(max_length=50)),
                ('apellido2', models.CharField(blank=True, max_length=50, null=True)),
                ('relacion', models.IntegerField(choices=[(1, 'Otros'), (2, 'Hijo/a'), (3, 'Cónyuge'), (4, 'Padre/Madre'), (5, 'Hermano/a'), (6, 'Vecino/a'), (7, 'Amigo/a'), (8, 'Familiar')], default=1)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactos', to='monitoring.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(max_length=512, unique=True)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('tipo', models.IntegerField(choices=[(1, 'Edificio'), (2, 'Planta'), (3, 'Pasillo'), (4, 'Habitación'), (5, 'Cama'), (6, 'Baño / Aseo'), (7, 'Zona genérica')], default=7)),
                ('bloqueada', models.BooleanField(default=False)),
                ('zona_padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subzonas', to='monitoring.zona')),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='zona_asignada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitoring.zona'),
        ),
    ]
