# Generated by Django 5.2.7 on 2025-11-05 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zona',
            name='camas_ocupadas',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='zona',
            name='total_camas',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='zona_asignada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes', to='monitoring.zona'),
        ),
    ]
