# Generated by Django 5.2.7 on 2025-11-12 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_zona_camas_ocupadas_zona_total_camas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='tipo_enfermedad',
            field=models.CharField(choices=[('ninguna', 'Ninguna'), ('cardiaca', 'Cardíaca'), ('respiratoria', 'Respiratoria'), ('neurologica', 'Neurológica'), ('diabetes', 'Diabetes'), ('otra', 'Otra')], default='ninguna', max_length=20),
        ),
        migrations.AddField(
            model_name='empleado',
            name='zona_asignada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empleados_asignados', to='monitoring.zona'),
        ),
    ]
